<?php
// This file generated by Propel 1.3.0-dev convert-props target
return array (
  'propel' => 
  array (
    'datasources' => 
    array (
      'propel' => 
      array (
        'classes' => 
        array (
          'PageMapBuilder' => '../application/model/map/PageMapBuilder.php',
          'PagePeer' => '../application/model/PagePeer.php',
          'Page' => '../application/model/Page.php',
          'UserMapBuilder' => '../application/model/map/UserMapBuilder.php',
          'UserPeer' => '../application/model/UserPeer.php',
          'User' => '../application/model/User.php',
          'CredentialMapBuilder' => '../application/model/map/CredentialMapBuilder.php',
          'CredentialPeer' => '../application/model/CredentialPeer.php',
          'Credential' => '../application/model/Credential.php',
          'UserCredentialMapBuilder' => '../application/model/map/UserCredentialMapBuilder.php',
          'UserCredentialPeer' => '../application/model/UserCredentialPeer.php',
          'UserCredential' => '../application/model/UserCredential.php',
          'ResourceCredentialMapBuilder' => '../application/model/map/ResourceCredentialMapBuilder.php',
          'ResourceCredentialPeer' => '../application/model/ResourceCredentialPeer.php',
          'ResourceCredential' => '../application/model/ResourceCredential.php',
        ),
      ),
    ),
  ),
);